# 강의노트
### Numpy의 활용

In [2]:
import numpy as np

In [5]:
# 단일 객체 저장 및 불러오기

array = np.arange(0, 10)
np.save('saved.npy', array)  #객체 저장

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 복수 객체 저장 및 불러오기

array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array_1 = array1, array_2 = array2)

data = np.load('saved.npz')
result1 = data['array_1']
result2 = data['array_2']

print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [20]:
# 원소의 정렬 (기본은 오름차순)

array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

[ 1  3  5  9 10]


In [22]:
# 내림차순

print(array[::-1])

[10  9  5  3  1]


In [26]:
# 각 열을 기준으로 정렬 (오름차순)

array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(array)
array.sort(axis = 0)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [28]:
# 균일한 간격으로 데이터 생성

array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [120]:
# 난수의 재연 (실행마다 결과 동일)

np.random.seed(7) #랜덤으로 발생되는 난수의 특정 값을 고정가능
print(np.random.randint(0, 10, (2, 3)))

[[4 9 6]
 [3 3 7]]


In [122]:
# 배열 객체 복사

array1 = np.arange(0, 10)
array2 = array1
array2[0] = 99
print(array1)  #array2를 수정했는데 array1값이 변경됨.

[99  1  2  3  4  5  6  7  8  9]


In [124]:
array1 = np.arange(10)
array2 = array1.copy()
array2[0] = 99

print(array1)
print(array2) #array2만 수정 가능

[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]


In [127]:
# 중복된 원소 제거

array = np.array([1,2,1,1,1,2,2,3,3,4])
print(np.unique(array))
print(array)

array = np.unique(array)
print(array)

[1 2 3 4]
[1 2 1 1 1 2 2 3 3 4]
[1 2 3 4]
